%global optflags %{optflags} -O3

Summary:	The GNU versions of find utilities (find and xargs)
Name:		findutils
Version:	4.7.0
Release:	1
License:	GPLv3
Group:		File tools
Url:		http://www.gnu.org/software/findutils/findutils.html
Source0:	ftp://alpha.gnu.org/gnu/findutils/%{name}-%{version}.tar.xz

# do not build locate
Patch1:		https://src.fedoraproject.org/rpms/findutils/raw/master/f/findutils-4.5.15-no-locate.patch
# add a new option -xautofs to find to not descend into directories on autofs file systems
Patch3:		https://src.fedoraproject.org/rpms/findutils/raw/master/f/findutils-4.4.2-xautofs.patch
# eliminate compile-time warnings
Patch4:		https://src.fedoraproject.org/rpms/findutils/raw/master/f/findutils-4.5.13-warnings.patch
# test-lock: disable the rwlock test
Patch10:	https://src.fedoraproject.org/rpms/findutils/raw/master/f/findutils-4.6.0-test-lock.patch
# implement the -noleaf option of find (#1252549)
Patch12:	https://src.fedoraproject.org/rpms/findutils/raw/master/f/findutils-4.6.0-leaf-opt.patch
Patch20:	findutils-4.6.0-fallthrough.patch

BuildRequires:	texinfo
BuildRequires:	gettext-devel

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a filename pattern). The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%prep
%autosetup -p1
rm -rf locate

%build
# Don't build or install locate because it conflicts with slocate,
# which is a secure version of locate.
sed -i '/^SUBDIRS/s/locate//' Makefile.in
libtoolize --copy --force
autoreconf -fiv

%configure \
	--enable-leaf-optimisation \
	--enable-d_type-optimization \
	--with-packager="%{vendor}" \
	--with-packager-bug-reports="%{bugurl}" \
	--with-fts

%make_build

%check
# fails because they need py2
make check

%install
%make_install

install -d %{buildroot}/bin
mv %{buildroot}%{_bindir}/find %{buildroot}/bin
ln -sf ../../bin/find %{buildroot}%{_bindir}/find
# (tpg) compat symlink
ln -sf ../../bin/find %{buildroot}%{_bindir}/oldfind

%find_lang %{name}

%files -f %{name}.lang
%doc NEWS README
/bin/find
%{_bindir}/find
%{_bindir}/oldfind
%{_bindir}/xargs
%{_mandir}/man1/find.1*
%{_mandir}/man1/xargs.1*
%{_infodir}/find*
